modules:
    - dachlatten-android
    - dachlatten-compose
    - dachlatten-datetime
    - dachlatten-debug
    - dachlatten-flow
    - dachlatten-google
    - dachlatten-markdown
    - dachlatten-primitives
    - dachlatten-retrofit
