[versions]
agp = "8.1.1"
kotlin = "1.9.10"
junit = "4.13.2"
coroutines = "1.7.3"
turbine = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
