name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    paths-ignore:
      - 'README.md'

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build release with Gradle
        run: ./amper test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: '**/build/reports/**/**/*.xml'
